### ISSUE TITLE
Unable to use image wrap function

### ISSUE THREAD

**Issue by riti1302** [zpincus/celltool#3]
Hi @zpincus ,
I'm trying to run your warp_images function and I'm confused what to pass as "output region". I'm passing the following tuple but getting a "invalid shape for coordinate array" error.
tuple - (0, 0, image.shape[0], image.shape[1])
Error - 
Traceback (most recent call last):
  File "wrap2.py", line 117, in <module>
    print(warp_images(from_points, to_points, [image], (0, 0, image.shape[0], image.shape[1])))
  File "wrap2.py", line 26, in warp_images
    return ndimage.map_coordinates(numpy.asarray(image), transform, order=interpolation_order)
  File "/home/ritika/anaconda3/envs/shipmnts/lib/python3.7/site-packages/scipy/ndimage/interpolation.py", line 341, in map_coordinates
    raise RuntimeError('invalid shape for coordinate array')
RuntimeError: invalid shape for coordinate array

**Comment by zpincus** [comment]
It seems like the `warp_images` function that's causing you problems is defined in your own code, from file `wrap2.py`. I guess that this copied from `celltool/numerics/image_warp.py:warp_images()`, but it's hard to tell exactly what's going on.

Can you post a self-contained example (calling into celltool code) that reproduces the problem, so I can take a look at what's happening here?

**Comment by lastapple** [comment]
I have met the same problem. I found that is because the input image has multi channels. So I split the image and it works.

def warp_images(from_points, to_points, image, output_region, interpolation_order = 1, approximate_grid=2):
    start = time.time(
    transform = _make_inverse_warp(from_points, to_points, output_region, approximate_grid)
    start1 = time.time()
    print("time:", start1-start)
    channel1 = np.expand_dims(ndimage.map_coordinates(image[:,:,0], transform, order=interpolation_order), axis=2)
    channel2 = np.expand_dims(ndimage.map_coordinates(image[:,:,1], transform, order=interpolation_order) , axis=2)
    channel3 = np.expand_dims(ndimage.map_coordinates(image[:,:,2], transform, order=interpolation_order), axis=2)
    start2 = time.time()
    print("time:", start2-start1)
    return np.concatenate((channel1,channel2,channel3),axis=2)
